name: Build package

on:
  workflow_call:
    secrets:
      DEPLOYBOT_EMAIL:
        required: true
      DEPLOYBOT_USER:
        required: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    env:
      NO_CHANGES: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Build assets
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Setup Git
        run: |
          git config --global user.email "${{ secrets.DEPLOYBOT_EMAIL }}" 
          git config --global user.name "${{ secrets.DEPLOYBOT_USER }}"
          git config --global advice.addIgnoredFile false
          git config --global push.autoSetupRemote true

      - name: Switch to "dev" branch if not on a tag
        if: ${{ github.ref_type != 'tag' }}
        run: |
          git checkout dev

      - name: Git add, commit
        run: |
          git add -f assets/ vendor/
          git commit -m "[BOT] Build package" --no-verify || ((echo "NO_CHANGES=yes" >> $GITHUB_ENV) && (echo "No changes to commit"))

      - name: Git push
        if: ${{ env.NO_CHANGES != 'yes' }}
        run: git push

      - name: Move tag
        if: ${{ github.ref_type == 'tag' && env.NO_CHANGES != 'yes' }}
        run: |
          git tag -d ${{ github.ref_name }}
          git push origin :refs/tags/${{ github.ref_name }}
          git tag ${{ github.ref_name }}
          git push origin --tags
