name: Release

on:
  workflow_call:
    secrets:
      DEPLOYBOT_EMAIL:
        required: true
      DEPLOYBOT_USER:
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name into env
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG_NAME }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Build assets
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Setup Git
        run: |
          git config --global user.email "${{ secrets.DEPLOYBOT_EMAIL }}" 
          git config --global user.name "${{ secrets.DEPLOYBOT_USER }}"
          git config --global advice.addIgnoredFile false
          git config --global push.autoSetupRemote true

      - name: Git add, commit, push
        run: |
          git add .
          git commit -m "[BOT] Build package" --no-verify
          git push

      - name: Move tag
        run: |
          git tag -d ${{ env.TAG_NAME }}
          git push origin :refs/tags/${{ env.TAG_NAME }}
          git tag ${{ env.TAG_NAME }}
          git push origin --tags
